### ISSUE TITLE
Sharing progress

### ISSUE THREAD

**Issue by Asimov4** [JsonBrown/mumble-alexa-connect#1]
Hi!
I am also interested in setting this up and was curious to know how far you got.

**Comment by JsonBrown** [comment]
it is working. I have not written any docs on it though.

 you need 3 projects plus a mumble server.
https://github.com/JsonBrown/mumble-alexa-bot
https://github.com/JsonBrown/mumble-alexa-auth
https://github.com/JsonBrown/mumble-alexa-connect

### Authentication
In order to authenticate, you will need to create an Alexa Voice Services device, then use the device serial and secret to generate a token and bind it to your amazon account,

- go to https://developer.amazon.com/edw/home.html#/
- create/login with an amazon developer account
- create a new AVS device
- use the clientid, and secret in mumble-alexa-auth/config/config.json
- then start mumble-alexa-auth
- to authorize the device to your amazon account, use the device id
```
curl https://localhost:9745/device/regcode/my_device/<deviceId> -k > ./config/deviceSecret.json

open https://localhost:9745/device/register/<regCode>

You will get a "This server could not prove that it is localhost; its security certificate is not trusted by your computer's operating system" warning. Since it's just localhost you can proceed.

# redirect url
#https://localhost:9745/authresponse/?code=<code>&scope=<scope>&state</state>

curl https://localhost:9745/device/accesstoken/my_device/<deviceId>/<deviceSecret> -k > ./config/token.json
```
it might be helpful to read up about amazon's tokens to learn about the refresh procedure, mumble-alexa-auth should refresh for you once it is setup correctly

### start the translation layer
once the device is authenticated, open mumble-alexa-connect and populate the /config/auth.json with the address and port of mumble-alexa-auth, and the device secret and id and the product serial number. also copy token.json into the config folder

start mumble-alexa-connect

### start the bot and connect it to mumble
open mumble-alexa-bot and update /config/config.json with the url of the mumble server and also the url of the translation layer

start mumble-alexa-bot

you should then see a user named alexa at the root of the server, and it will respond to your requests. since it is bound to your amazon account, http://alexa.amazon.com should show you what it hears.

**Comment by jonydevcoder** [comment]
This project looks awesome, i am trying to do that setup but mumble-alexa-auth cant start:
 ```
    $ npm install 
    $ node server.js
 ```

1. First i had:
```
  Error: ENOENT: no such file or directory, open './ssl/server.key'
  Error: ENOENT: no such file or directory, open './ssl/server.crt'
```
2. To solve this error I had to generate the certs defined [here](https://github.com/JsonBrown/mumble-alexa-auth/blob/master/server.js#L12) with:
```
  openssl genrsa 2048 > ./ssl/server.key
  openssl req -new -x509 -nodes -sha256 -days 365 -key server.key -out server.crt
```
3. Now i am blocked here:
```
  node server.js 
  Listening on port 9745
  /home/mumble/projects/JsonBrown/mumble-alexa-auth/node_modules/sqlite3/lib/trace.js:27
                      throw err;
                      ^

  TypeError: Cannot read property 'key' of undefined
      at /home/mumble/projects/JsonBrown/mumble-alexa-auth/authentication.js:84:19
      at Statement.errBack (/home/mumble/projects/JsonBrown/mumble-alexa- 
 auth/node_modules/sqlite3/lib/sqlite3.js:16:21)
  --> in Database#each('SELECT key, deviceSecret, accessToken, refreshToken, tokenExpires FROM 
  Devices', [Function])
      at GetDeviceInfo (/home/mumble/projects/JsonBrown/mumble-alexa-auth/authentication.js:83:6)
      at Object.<anonymous> (/home/mumble/projects/JsonBrown/mumble-alexa- 
  auth/authentication.js:38:27)
      at Module._compile (module.js:652:30)
      at Object.Module._extensions..js (module.js:663:10)
      at Module.load (module.js:565:32)
      at tryModuleLoad (module.js:505:12)
      at Function.Module._load (module.js:497:3)
      at Module.require (module.js:596:17)
      at require (internal/module.js:11:18)
```

Could you give me a hand ?

**Comment by JsonBrown** [comment]
@jonydevcoder 
it sounds like your sql lite db wasn't created correctly. 
1) make sure you have DeviceInfo.db in the alex-auth folder
2) if you do make sure the "Devices" table was created correctly in it. if not.. try deleting DeviceInfo.db and restart the service.

**Comment by jonydevcoder** [comment]
Thankyou @JsonBrown , it is up now, but i have some troubles registering my device
```
mumble-alexa-auth$ node server.js 
Listening on port 9745
```

Now i am struggling with the 6th point with no success:
- to authorize the device to your amazon account, use the device id

**I do:**
```
$ curl https://localhost:9745/device/regcode/alexa_mumble/1234 -k > ./config/deviceSecret.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   104  100   104    0     0   2326      0 --:--:-- --:--:-- --:--:--  2418
```
**So ./config/deviceSecret.json content is:**
```
{"regCode":"223c9blabla","deviceSecret":"3d46eblabla","expires":1555620718334}
```

Then I open de browser and go to `https://localhost:9745/device/register/223c9blabla` and it gives the following error

![image](https://user-images.githubusercontent.com/49318032/56390047-53c44c00-622b-11e9-9893-b7c0d4c37199.png)



Could you give me a hand with this?

**Comment by JsonBrown** [comment]
@jonydevcoder 
you will have to 
1) create an amazon developer account
2) create an AVS application to gain access to  the Alexa APIs.

if you have done both of these. then you simply update the security profile in your AVS app to have 
the redirect url
![image](https://user-images.githubusercontent.com/2814830/56390997-088e4700-61f3-11e9-965f-ed8caa4d54ce.png)

**Comment by jonydevcoder** [comment]
I did that before but it still saying:
```
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal.
```
I have the same config.

![image](https://user-images.githubusercontent.com/49318032/56392886-faf8b180-6232-11e9-8265-04721b1a84b5.png)

Also i tested with https://localhost:9745 in `Allowed origins` (Origins must use the HTTPS protocol. If your website will use the Login with Amazon SDK for Javascript, add your website origin here – a combination of protocol, domain name and port (for example: https://www.example.com:8443). If you are using standard port 443, you only need to include the domain name (for example: https://www.example.com).

**Comment by JsonBrown** [comment]
@jonydevcoder 
is it possible that the redirect_url is not being urlencoded correctly. I'll have to try this again as it has been a while since I obtained a token.

the good news is that you only have to get a token once.
